title: "Aliou BA"
logo: img/WhatsApp%20Image%202026-01-30%20at%2011.57.17.jpeg
description: "Portfolio Data Scientist – IA, Data Science, Développeur"
show_downloads: true
theme: jekyll-theme-minimal
lang: fr
